### ISSUE TITLE
3 cores max?

### ISSUE THREAD

**Issue by vgeo999** [mikajoh/stmprinter#3]
Hi guys, 

thank you very much for your package! At the moment, I think it might be really useful for my work. 
I'm new to the parallel computing world, so just a quick question for understanding:
When I use parallel::detectCores() it tells me I have 8 cores to available, but many_models() uses only 3 of them, consequently, no matter what input I use or how I set function parameters. Does this mean, my type of calculation is not suitable for more than 3 cores? Or does your function use 3 cores max. per default?

Thanks again and have a nice evening, 
Liz

**Comment by mikajoh** [comment]
Hi! Not sure whats going on. Could share the code? Or preferably, a reproducible example.

**Comment by vgeo999** [comment]
Hi, thanks for the quick response! It is already good to know that this is no desired behaviour. Now, I set a meeting with the IT guy from our university. Maybe it has something to do with the cloudsystem my code is running on. I'll let you know next week if I've found the solution on our side, otherwise I will start building a reproducible example on the weekend. Thanks again and best regards, Liz

**Comment by vgeo999** [comment]
Hi, 
it's working now! Seemed it was a VM core assigning problem, sorry for bothering you! 
I like the progress bar when running many_models(). Thanks for this nice improvement.

**Comment by mikajoh** [comment]
Awesome!
